version: "3.4"

services:
  lds:
    image: lds:latest
    build:
      dockerfile: Dockerfile
    #hostname: lds
    #ports:
    #  - 5353:5353/udp
    #  - 4840:4840
    restart: always
    tty: true
    volumes:
      - ./UALDS-data/config:/lds/etc
      - ./UALDS-data/pki:/opt/opcfoundation/ualds/pki
      - ./UALDS-data/logs:/var/log/
    # using network_mode: host to ensure working mDNS Broadcast/Receive
    # alternatively you can uncomment the port config - make sure to properly set the hostname, so the mDNS Broadcast points to your actual host
    network_mode: host
